# .github/workflows/dispatch_update.yml in submodule repo
name: Dispatch Update Main Repo
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch update to Main Repo
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.trigger_token }}
          repository: mikewebbtech/mikewebbtech-hugo
          event-type: submodule_event
          client-payload: '{"submodule_name": "content/articles", "commit_sha": "${{ github.sha }}"}'
